public with sharing class DemoClass {
    /* Push to new branch */
    /* Push to new branch new*/
    /* Add Test comment 1*/
    /* Add Test comment 2 */
    /* Add Test comment 3 */
    /* Add Test comment 4 */
    /* Add Test comment 5 */
    /* Add Test comment 6 */
    /* Add Test comment in emc-priyanka-demofeature2 branch*/
    public DemoClass() {
        Decimal a = 6+6;
        System.debug('Test class: ' + a);
    }
}